In [2]:
import torch


In [3]:
randint = torch.randint(-100,100,(6,))
randint
randint2 = torch.randint(5,(5,))
randint2

tensor([4, 0, 0, 1, 0])

In [4]:
tensor = torch.tensor([[0.1,1.2],[2.2,3.1],[4.9,5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2,3)
zeros


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=10,end=10,steps = 5)
logspace

tensor([1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2,3),dtype = torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [13]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [14]:
probabilities = torch.tensor([0.1,0.9])

samples = torch.multinomial(probabilities, num_samples = 10,replacement = True)
samples

tensor([1, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [15]:
tensor = torch.tensor([1,2,3,4])
## concatination
out = torch.cat((tensor,torch.tensor([5])),dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [16]:
## triangle upper triu

out = torch.triu(torch.randint(-100,100,(5,5)))
out

tensor([[-43,  92, -26,  24, -36],
        [  0,  24,  69,  10,  58],
        [  0,   0, -93,  67,  42],
        [  0,   0,   0,  13,  52],
        [  0,   0,   0,   0,  64]])

In [17]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [19]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [20]:
input = torch.zeros(2,3,4)
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [21]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1,tensor2,tensor3])
stacked_tensor


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
import torch.nn as nn

sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3,3,bias = False)
print(linear(sample))

tensor([-9.2025, -0.6160, -6.4558], grad_fn=<SqueezeBackward4>)


In [23]:
import torch.nn.functional as F
tensor1 = torch.tensor([1.0,2.0,3.0])
softmax_output = F.softmax(tensor1,dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [24]:
## embeddings
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size,embedding_dim)

input_indices = torch.LongTensor([1,5,3,2])

embedded_output = embedding(input_indices)

print(embedded_output.shape)

torch.Size([4, 100])


In [25]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])

a @ b
torch.matmul(a,b)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [26]:
int_64 = torch.randint(1,(3,2)).float()

float_32 = torch.rand(2,3)

result = torch.matmul(int_64,float_32)

In [27]:
a = torch.rand(2,3,5)
print(a.shape)
x,y,z = a.shape
a = a.view(x,y,z)
# print(x,y,z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [28]:
import torch.nn as nn
vocab_size = 6
token_embedding_table = nn.Embedding(vocab_size,vocab_size)
print(token_embedding_table,'This is the embedding')


index = torch.tensor([[0, 1, 2],[1,4,5]])


logits = token_embedding_table(index)
print(logits,'this is logits')
b,t,c = logits.shape

Embedding(6, 6) This is the embedding
tensor([[[-0.9401,  0.4899,  1.1737,  0.6869, -0.0865, -1.1344],
         [ 0.3351,  0.3462, -1.9393,  0.6430, -1.1752,  1.3683],
         [ 0.4847,  0.2558,  0.8049, -0.3266,  1.6236,  0.2143]],

        [[ 0.3351,  0.3462, -1.9393,  0.6430, -1.1752,  1.3683],
         [ 0.7900, -0.5231,  1.9024, -0.7804, -1.3707,  0.5472],
         [ 2.3455, -0.3964,  0.2356, -0.2217,  0.8984,  0.0528]]],
       grad_fn=<EmbeddingBackward0>) this is logits


In [29]:
a = logits.view(b*t,c)
a

tensor([[-0.9401,  0.4899,  1.1737,  0.6869, -0.0865, -1.1344],
        [ 0.3351,  0.3462, -1.9393,  0.6430, -1.1752,  1.3683],
        [ 0.4847,  0.2558,  0.8049, -0.3266,  1.6236,  0.2143],
        [ 0.3351,  0.3462, -1.9393,  0.6430, -1.1752,  1.3683],
        [ 0.7900, -0.5231,  1.9024, -0.7804, -1.3707,  0.5472],
        [ 2.3455, -0.3964,  0.2356, -0.2217,  0.8984,  0.0528]],
       grad_fn=<ViewBackward0>)

In [89]:
logits = torch.tensor([
    [
        [0.1, 0.2, 0.3],  # First token in the first sequence
        [0.4, 0.5, 0.6],  # Second token in the first sequence
        [0.7, 0.8, 0.9],  # Third token in the first sequence
        [1.0, 1.1, 1.2],  # Fourth token in the first sequence  
        [1.3, 1.4, 1.5]
    ]]) # Fifth token in the first sequence

# print(logits[:,-1,:])

#     ],


#     [
#         [1.6, 1.7, 1.8],  # First token in the second sequence
#         [1.9, 2.0, 2.1],  # Second token in the second sequence
#         [2.2, 2.3, 2.4],  # Third token in the second sequence
#         [2.5, 2.6, 2.7],  # Fourth token in the second sequence
#         [2.8, 2.9, 3.0]   # Fifth token in the second sequence
#     ]
# ]) 
logits.transpose(-2,-1)

tensor([[[0.1000, 0.4000, 0.7000, 1.0000, 1.3000],
         [0.2000, 0.5000, 0.8000, 1.1000, 1.4000],
         [0.3000, 0.6000, 0.9000, 1.2000, 1.5000]]])

In [81]:
lis = [0.0235, 0.0038, 0.0121, 0.0039, 0.0073, 0.0045, 0.0076, 0.0185, 0.0056,
         0.0105, 0.0051, 0.0043, 0.0099, 0.0022, 0.0007, 0.0010, 0.0202, 0.0159,
         0.0320, 0.0020, 0.0003, 0.0089, 0.0091, 0.0037, 0.0046, 0.0026, 0.0041,
         0.0068, 0.0088, 0.0100, 0.0026, 0.0192, 0.0667, 0.0144, 0.0041, 0.0214,
         0.0103, 0.0325, 0.0361, 0.0035, 0.0110, 0.0074, 0.0137, 0.0028, 0.0074,
         0.0083, 0.0064, 0.0034, 0.0051, 0.0032, 0.0677, 0.0018, 0.0018, 0.0109,
         0.0033, 0.0072, 0.0035, 0.0214, 0.0084, 0.0061, 0.0207, 0.0080, 0.0153,
         0.0144, 0.0025, 0.0276, 0.0797, 0.0107, 0.0024, 0.0223, 0.0454, 0.0202,
         0.0100, 0.0096, 0.0045, 0.0046, 0.0266, 0.0055, 0.0013, 0.0027, 0.0047]


In [32]:
import torch
import torch.nn as nn
import torch.optim as optim

# Example model with a single linear layer
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.linear = nn.Linear(1, 1, bias=False)  # Linear layer: y = wx

    def forward(self, x):
        return self.linear(x)

# Instantiate the model
model = SimpleModel()

# Example data
x_train = torch.tensor([[2.0]], requires_grad=True)
y_train = torch.tensor([[4.0]])

# Loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Forward pass
outputs = model(x_train)
loss = criterion(outputs, y_train)

# Print initial loss
print(f"Initial loss: {loss.item()}")

# Backward pass
loss.backward()

# Print gradients
print(f"Gradients before zeroing: {model.linear.weight.grad}")

# Zero gradients
optimizer.zero_grad()

# Print gradients after zeroing
print(f"Gradients after zeroing: {model.linear.weight.grad}")

# Update parameters
optimizer.step()

# Print updated weight
print(f"Updated weight: {model.linear.weight.item()}")


Initial loss: 18.78175163269043
Gradients before zeroing: tensor([[-17.3352]])
Gradients after zeroing: None
Updated weight: -0.16689586639404297


In [33]:

import torch.nn as nn
token_embedding_table = nn.Embedding(vocab_size,vocab_size)
context = torch.zeros((1,1),dtype = torch.long)
print(context)
# print(token_embedding_table(context))
# print(token_embedding_table(logits))



tensor([[0]])


In [34]:
chars = ['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']

In [35]:
string_to_int = {ch:i for i, ch in enumerate(chars)}
int_to_string = {i:ch for i ,ch in enumerate(chars)}


In [36]:
int_to_string[32]

'H'

In [37]:
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])

In [38]:
enc = encode('hello')
enc

[61, 58, 65, 65, 68]

In [39]:
decode(enc)

'hello'